### ISSUE TITLE
PackagesNotFoundError on conda installation

### ISSUE THREAD

**Issue by ashimgiyanani** [P403n1x87/austin#130]
### Description

Cannot import austin within conda

### Steps to Reproduce

1. conda install -c conda-forge austin

**Expected behavior:** 
Expect the conda installation to go through

**Actual behavior:** 

PackagesNotFoundError: The following packages are not available from current channels:
  - austin
Current channels:
  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

**Reproduces how often:**
forever

### Versions
conda 22.9.0

You can get this information from copy and pasting the output of `austin
--version` from the command line. Also, please include the OS and what version
of the OS you're running.
Windows 10 Enterprise 10.0.19044

**Comment by P403n1x87** [comment]
Thanks for reporting this. Unfortunately I am not the maintainer of the Austin package on conda, so you would have to raise this issue with them :slightly_frowning_face:. I believe this is due to the fact that Austin builds for Windows are not available from conda-forge. Please have a look at the installation alternatives for Windows, which include `choco`, `scoop`, as well as pre-built installers from the [releases](https://github.com/P403n1x87/austin/releases/tag/v3.3.0).
