### ISSUE TITLE
No samples collected

### ISSUE THREAD

**Issue by zdyj3170101136** [P403n1x87/austin#211]
### Description

```
[root@plat-sh-data-testing-common-pic-infer-demo001 ~]# austin -p 30932 -mem
              _   _
 __ _ _  _ __| |_(_)_ _
/ _` | || (_-<  _| | ' \
\__,_|\_,_/__/\__|_|_||_| 3.6.0 [gcc 9.4.0]
# austin: 3.6.0
# interval: 100
# mode: memory
# memory: 3879940

🐍 Python version: 3.7.7
```
^C
# duration: 3605829

😣 No samples collected.

#### version
cmd:
```
austin -p 30932 -mem
```

```
 austin version
              _   _
 __ _ _  _ __| |_(_)_ _
/ _` | || (_-<  _| | ' \
\__,_|\_,_/__/\__|_|_||_| 3.6.0 [gcc 9.4.0]

❌ Cannot launch the given command or it terminated too quickly.
```

python version:
```
[root@plat-sh-data-testing-common-pic-infer-demo001 ~]# /proc/30932/exe --version
Python 3.7.7
```

**Comment by P403n1x87** [comment]
@zdyj3170101136 Austin 3.6 has dropped support for CPython < 3.8. Please use Austin 3.5 if you need to profile CPython 3.7: `pip install austin-dist~=3.5.0`

**Comment by zdyj3170101136** [comment]
> pip install austin-dist~=3.5.0

not work, too.

i am sure that process 30932 is a python process and costing cpu.
```
[root@plat-sh-data-testing-common-pic-infer-demo001 ~]# austin -mem  -p  30932
              _   _
 __ _ _  _ __| |_(_)_ _
/ _` | || (_-<  _| | ' \
\__,_|\_,_/__/\__|_|_||_| 3.5.0 [GCC 9.4.0]
# austin: 3.5.0
# interval: 100
# mode: memory
# memory: 3879940

🐍 Python version: 3.7.7


^C
# duration: 21342104

😣 No samples collected.
```

**Comment by P403n1x87** [comment]
@zdyj3170101136 could you check that samples are collected in either wall time or CPU time mode, please? The commands would be
```
austin -p  30932
```
and
```
austin -sp  30932
```
respectively. Also note that the short option for memory is `-m`, not `-mem`.

Please note that, if the application is running but not allocating enough memory to cause changes in the resident memory levels, then Austin would not collect any samples. If you are interested in allocations rather than RSS, perhaps you could try the memory mode of [Echion](https://github.com/P403n1x87/echion) (note that this is still an experimental project). The output is the same as Austin in binary mode, i.e. MOJO. You could use the `mojo2austin` command from the [austin-python](https://github.com/P403n1x87/austin-python) package to convert to Austin non-binary format if needed.

**Comment by zdyj3170101136** [comment]
> @zdyj3170101136您能检查一下样本是在 Wall Time 模式还是 CPU Time 模式下收集的吗？命令是
> 
> ```
> austin -p  30932
> ```
> 
> 和
> 
> ```
> austin -sp  30932
> ```
> 
> 分别。另请注意，内存的简短选项是`-m`, not `-mem`。
> 
> 请注意，如果应用程序正在运行但没有分配足够的内存来导致驻留内存级别发生变化，则 Austin 将不会收集任何样本。如果您对分配而不是 RSS 感兴趣，也许您可​​以尝试[Echion](https://github.com/P403n1x87/echion)的内存模式（请注意，这仍然是一个实验项目）。输出与二进制模式下的Austin相同，即MOJO。如果需要，您可以使用[austin-python](https://github.com/P403n1x87/austin-python)`mojo2austin`包中的命令转换为 Austin 非二进制格式。[](https://github.com/P403n1x87/austin-python)

i think the austin output is not correct.

my benchmark.py read lots of file and call image.tobytes tran them to bytes.

austin shows that only 30% of memory account for func tobytes, which is 90% percent in actual.
```
austin -m pip  -o b python3  benchmakr.py

cat b | sed '/^#/d' | FlameGraph/flamegraph.pl --countname=μs > test.svg
```

![截屏2024-01-22 下午12 47 57](https://github.com/P403n1x87/austin/assets/52686065/674851dd-3fa9-4b17-a50d-c9ea177d2e35)

**Comment by zdyj3170101136** [comment]
> > @zdyj3170101136您可以检查一下样本是在 Wall Time 模式还是 CPU Time 模式下收集的吗？命令是
> > ```
> > austin -p  30932
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 和
> > ```
> > austin -sp  30932
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 分别。另外请注意，内存的简短选项是`-m`，而不是`-mem`。
> > 请注意，如果应用程序正在运行但没有分配足够的内存来导致驻留内存级别发生变化，则 Austin 将不会收集任何样本。如果您对分配而不是 RSS 感兴趣，也许您可​​以尝试[Echion](https://github.com/P403n1x87/echion)的内存模式（请注意，这仍然是一个实验项目）。输出与Austin下的二进制模式相同，即MOJO。如果需要，您可以使用[austin-python](https://github.com/P403n1x87/austin-python)`mojo2austin`包中的命令转换为Austin非二进制格式。
> 
> 我认为奥斯汀的输出不正确。
> 
> 我的 benchmark.py 读取了大量文件并调用 image.tobytes 将它们转换为字节。
> 
> austin 显示只有 30% 的内存占 func tobytes，实际占 90%。
> 
> ```
> austin -m pip  -o b python3  benchmakr.py
> 
> cat b | sed '/^#/d' | FlameGraph/flamegraph.pl --countname=μs > test.svg
> ```
> 
> ![截屏2024-01-22 下午12 47 57](https://private-user-images.githubusercontent.com/52686065/298461685-674851dd-3fa9-4b17-a50d-c9ea177d2e35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4OTkyNjEsIm5iZiI6MTcwNTg5ODk2MSwicGF0aCI6Ii81MjY4NjA2NS8yOTg0NjE2ODUtNjc0ODUxZGQtM2ZhOS00YjE3LWE1MGQtYzllYTE3N2QyZTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA0NDkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMWFlMzhkYTUzMzZkMmJlNTczOTNmNGFlZDljZTE1ZmM3ODQwOGYyMjE2OTEwODJjZmZlMjY5MWE3MGZkNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i2sJpW7BlHaHEE1weMLf3YJ9Oa_Otxw9XCqFqE0gdMc)

i use memray and scalene to test.

and the output is correct:
![image](https://github.com/P403n1x87/austin/assets/52686065/f14a627c-44ff-4442-bbfb-8fbb04378464)

**Comment by P403n1x87** [comment]
@zdyj3170101136 please note that Austin and memray/scalene measure different things. Austin is tracking the resident memory and making a best guess as to which call stack was responsible for any _variations_ (positive or negative). Memray/scalene trace memory allocations and attach them the actual stack that made those allocations. The "right" tool to use here depends on what one is trying to measure. Note that a memory allocation does not necessarily imply an increased usage in resident memory (e.g. because of [COW](https://en.wikipedia.org/wiki/Copy-on-write) optimisations etc...)
