### ISSUE TITLE
Can't run script with local package import 

### ISSUE THREAD

**Issue by StefanHeng** [P403n1x87/austin#212]
I'm able to profile from a sample script (simple for loop) to test the pipeline is working, e.g. 
```bash
sudo austin -i 1ms --pipe python test-lang.py > sample_test.austin
```

But when I actually use this for my use case: a script that imports a local package, I got `ModuleNotFoundError`, see below: 
```bash
➜ sudo austin -i 100 --pipe /Users/stefanhg/opt/anaconda3/envs/llm-ie-gen/bin/python "/Users/stefanhg/Documents/Georgia Tech/Research/LLM fo
r IE Data Gen/LLM-Data-Gen-IE/chore/generate.py" > generate.austin
Traceback (most recent call last):
  File "/Users/stefanhg/Documents/Georgia Tech/Research/LLM for IE Data Gen/LLM-Data-Gen-IE/chore/generate.py", line 2, in <module>
    from src.util import *
ModuleNotFoundError: No module named 'src'
```

**Comment by P403n1x87** [comment]
@StefanHeng I suspect this is due to the fact that the `src` folder is not on the `PYTHONPATH`. Does
```console
sudo /Users/stefanhg/opt/anaconda3/envs/llm-ie-gen/bin/python "/Users/stefanhg/Documents/Georgia Tech/Research/LLM for IE Data Gen/LLM-Data-Gen-IE/chore/generate.py"
```
work? My guess is that this command would fail with the same error. For this to work, I think you should set the `PYTHONPATH` to include the location of the `src` folder for the command _after_ sudo (or allow sudo to pass the `PYTHONPATH` variable over to the command).
