### ISSUE TITLE
Sampler associated time delta instead of number of samples

### ISSUE THREAD

**Issue by randomstuff** [P403n1x87/austin#23]
### Description

The value associated with each stack sample is the time difference between the current sample and the previous one (in microseconds):

```c
static int
_py_proc__sample(py_proc_t * py_proc) {
  ctime_t   delta     = gettime() - t_sample;
  // [...]
  _print_collapsed_stack(py_thread, delta, mem_delta >> 10);
  // [...]
  t_sample += delta;
}
```

This is different from what is expected from flamegraph and what is generated by (most?) flamegraph stackcollapse tools: they expecte/generate sample counts.

As a consequence, when passed to FlameGraph, the number of samples in the SVG is not correct.

I tyhink it would be more correct (and least suprising) to report the number of samples (by default). Alternatively, the behavious should be documented (and possibly and option to report by sample counts could be added).

**Comment by P403n1x87** [comment]
The output generated by Austin is documented in the README:

> Each line has the structure
> 
> `Thread [tid];[func] ([mod]);#[line no];[func] ...;L[line no] [usec]`

The reason why Austin reports time deltas rather than sample counts is that this way one also gets a measure of the clock time spent on each part of the application. If one prefers a sample count, this could be inferred from Austin's output by collecting the samples and replacing the time delta with a 1. Of course, one could introduce an option to switch to counts rather than time deltas. Happy to review a PR with the new feature :).

In the end, what really matters with a statistical profiler is that the ratios between aggregated figures are approximately invariant, as one cannot attach a particular meaning to a single count.

**Comment by randomstuff** [comment]
Yes I agree, this can be done as a post processing step.

**Comment by P403n1x87** [comment]
I'm closing this issue for now. If there will be a strong interest for such a feature to be built into Austin then it can be re-opened.
