### ISSUE TITLE
Subprocess.Popen is not followed when the Children flag is on

### ISSUE THREAD

**Issue by DamGouz** [P403n1x87/austin#236]
### Description

Running a subprocess with Popen causes austin to stop monitoring the children 

### Steps to Reproduce

```import subprocess
import os
import sys
import time

if __name__ == "__main__":
    if len(sys.argv) == 1:
        print(os.getpid())
        subprocess.call(['python', 'test.py', 'popen'])
    elif sys.argv[1] == 'popen':
        subprocess.Popen(['python', 'test.py', 'count'])
    elif sys.argv[1] == 'count':
        for i in range(100):
            print(i)
            time.sleep(0.1)
```

**Expected behavior:** 
I would expect austin to monitor all 3 calls of the script, up to counting to 100.

**Actual behavior:** 
It stops at Popen:
`P55636;T0:5c98;C:\tmp\austin_test\test.py:<module>:9;C:\python\Lib\subprocess.py:call:391;C:\python\Lib\subprocess.py:Popen.wait:1264;C:\python\Lib\subprocess.py:Popen._wait:1588 36`

**Reproduces how often:** 
100%

### Versions
3.6.0

**Comment by P403n1x87** [comment]
@DamGouz thanks for reporting this. Technically, Austin is doing what it was designed to do in this case, which is sample as long as the parent process is running. When the parent process terminates, Austin also terminates, therefore no more (child) processes will be tracked and sampled. When the parent disappears, it becomes tricky to maintain a process sub-tree because the root of the tree disappears, and one would have to deal with multiple rooted trees in general. Normally, I would say somebody calling `Popen` would also wait for the subprocess to terminate. If you run this code instead

```python
import os
import subprocess
import sys
import time

if __name__ == "__main__":
    if len(sys.argv) == 1:
        print(os.getpid())
        subprocess.call(["python", "test.py", "popen"])
        print("bye")
    elif sys.argv[1] == "popen":
        p = subprocess.Popen(["python", "test.py", "count"])
        p.wait()
    elif sys.argv[1] == "count":
        for i in range(100):
            print(i)
            time.sleep(0.1)
```
then you should get this (wall time) flame graph
<img width="1158" alt="Screenshot 2024-10-13 at 11 18 03" src="https://github.com/user-attachments/assets/26b4fd94-2d85-43ed-87f7-a77581a076a1">
