### ISSUE TITLE
Austin doesn't work with Speedscope anymore?

### ISSUE THREAD

**Issue by siboehm** [P403n1x87/austin#91]
### Description

With `austin=2.1.1` the austin output could be uploaded directly to Speedscope, but this broke with 3.0

### Steps to Reproduce

1. `conda install austin==3.1`
2. `austin -o austin_3_1.txt python -c 'import this'`
3. upload austin_3_1.txt to speedscope

**Expected behavior:** Speedscope displays flamegraph, just like with `austin==2.1.1`

**Actual behavior:** "Unrecognized format! See documentation about supported formats."

**Reproduces how often:** 100%

Is this expected behaviour? I realize that there is a `austin2speedscope` CLI tool, but from the README it sounds like using it is optional. I couldn't figure out a way to pipe to `austin2speedscope`.

I really like using austin and speedscope, but having a necessary conversion step is a bit unpractical. Ideally I'd like it for speedscope to directly support the new format. Other options would be a flag eg `austin --speedscope-format` or allowing piping to `austin2speedscope`. With the current versions I have 2 very large profiling outputs on disk, one in the original format, one in the speedscope format.

(I didn't know where to open this issue, I hope here is fine).

**Comment by P403n1x87** [comment]
Thanks for reporting this. Austin 3 introduced metadata in the output which breaks the current deployment of speedscope.app. Some time ago I opened a PR to fix this, which got merged (https://github.com/jlfwong/speedscope/pull/336), but as far as I can tell these changes are not live yet. Hence, in my view, this is an issue with speedscope more than with Austin.

There are a couple of ways of getting around this. I'd recommend using the `austin2speedscope` conversion tool, as the data representation in the UI would be nicer. The help message states

~~~
sage: austin2speedscope [-h] [--indent INDENT] [-V] input output

Convert Austin generated profiles to the Speedscope JSON format accepted by https://speedscope.app. The output will contain a profile for each thread and metric included in the input file.

positional arguments:
  input            The input file containing Austin samples in normal format.
  output           The name of the output Speedscope JSON file.

optional arguments:
  -h, --help       show this help message and exit
  --indent INDENT  Give a non-null value to prettify the JSON output.
  -V, --version    show program's version number and exit
~~~
hence, to convert `foo.austin` to `foo.json`, simply do
~~~
austin2speedscope foo.austin foo.json
~~~

Alternatively, you could filter out all the lines that do not start with a `P` using `sed` with, e.g.
~~~
sed -nr '/^P/p' foo.austin > foo.ss.austin
~~~
I appreciate both solutions require processing the output from Austin. The latter could be combined with the `austin` command to give a one-liner though, e.g.
~~~
austin python -c 'import this' | sed -nr '/^P/p' > austin_3_1.txt
~~~

Finally, just a side note to point out that the latest release of `austin-python` comes with an `austin-compress` tool that can reduce the size of profile files by aggregating identical stack samples in the output:

~~~
usage: austin-compress [-h] [-c] [-V] input output

Compress a raw Austin sample file by aggregating the collected samples.

positional arguments:
  input          The input file containing Austin samples.
  output         The output file; defaults to the input file for in-place compression.

optional arguments:
  -h, --help     show this help message and exit
  -c, --counts   Use sample counts instead of measured sampling durations.
  -V, --version  show program's version number and exit
~~~

I hope either of these solutions is acceptable.

**Comment by P403n1x87** [comment]
> I think it'd be nice if something like `austin python -c 'import this' | austin2speedscope outfile.txt` would work (or `austin python -c 'import this' | austin-compress | austin2speedscope outfile.txt` for that matter).

That's a great suggestion, thanks! I'll keep this in mind for future releases of `austin-python`! :slightly_smiling_face:
