### ISSUE TITLE
Please update Ubuntu repo's with new Austin version.

### ISSUE THREAD

**Issue by cyraid** [P403n1x87/austin#96]
### Description

Very old version on Ubuntu repository 20.10 (1.0.1)
Or create a PPA would be nice too!

### Steps to Reproduce

1. apt install
2. austin --version
3. read the version "1.0.1"

**Expected behavior:** Need new version with --pipe

**Actual behavior:** Old version.

**Reproduces how often:** Every time.

### Versions

1.0.1

**Comment by P403n1x87** [comment]
@cyraid sorry for this. Unfortunately, packaging Austin for Debian is becoming a bit too stressful due to having to follow up with mentors and stuff, so I have stopped maintenance. Perhaps grabbing Austin from the [GitHub Releases page](https://github.com/P403n1x87/austin/releases/latest) might work for you for the time being?

**Comment by cyraid** [comment]
@P403n1x87 It's all good I ended up just compiling it from source and using it. :) It's alright, no worries.
